import { z } from "zod";
import * as db from "../db";
import { filterByScope, requirePermission } from "../access";
import { adminProcedure, protectedProcedure, router } from "../_core/trpc";

const text = (label: string, max = 160) => z.string().trim().min(1, `${label} là bắt buộc`).max(max);
const quantity = z.coerce.number().min(0, "Giá trị không được âm").max(999999999);
const date = z.coerce.date();

const plotRow = z.object({
  code: text("Mã lô", 48), name: text("Tên lô", 160), unit: text("Đơn vị", 120), gardenType: z.enum(["A", "B", "C"]).optional().nullable(), tappingDay: z.coerce.number().int().min(1).max(31).optional().nullable(), rowStart: z.coerce.number().int().positive().max(99999).optional().nullable(), rowEnd: z.coerce.number().int().positive().max(99999).optional().nullable(), areaHa: z.coerce.number().positive("Diện tích phải lớn hơn 0").max(999999), note: z.string().max(4000).optional().nullable(),
  plantedYear: z.coerce.number().int().min(1900).max(2100).optional().nullable(), cultivar: z.string().max(160).optional().nullable(), inventoryPits: z.coerce.number().int().min(0).optional().nullable(), inventoryTrees: z.coerce.number().int().min(0).optional().nullable(), tappingTrees: z.coerce.number().int().min(0).optional().nullable(), tappingDensity: quantity.optional().nullable(), plotRank: z.string().max(12).optional().nullable(),
}).refine(row => !row.rowStart || !row.rowEnd || row.rowStart <= row.rowEnd, { message: "Từ hàng phải nhỏ hơn hoặc bằng Đến hàng" });
const workerRow = z.object({ unit: text("Đội", 120), name: text("Tên", 160), employeeCode: z.string().max(64).optional().nullable(), phoneticName: z.string().max(160).optional().nullable(), gender: z.enum(["male", "female"]), status: z.enum(["active", "inactive"]), roleTitle: z.string().max(120).optional(), note: z.string().max(1000).optional().nullable() });
const workerCodeRow = z.object({ unit: text("Đội", 120), phoneticName: text("Tên phiên âm", 160), employeeCode: text("Mã số", 64) });
const plotIndicatorRow = z.object({ code: text("Mã lô", 48), indicatorDate: date, inventoryPits: quantity.optional().nullable(), inventoryTrees: quantity.optional().nullable(), tappingTrees: quantity.optional().nullable(), immatureTrees: quantity.optional().nullable(), nonproductiveTrees: quantity.optional().nullable(), diseasedTrees: quantity.optional().nullable(), dryTappingTrees: quantity.optional().nullable(), emptyPits: quantity.optional().nullable(), tappingDensity: quantity.optional().nullable(), plotRank: z.string().max(12).optional().nullable() });
const teamImportRow = z.object({ unit: text("Đội", 120), gardenName: text("Vườn", 160), periodLabel: text("Đợt", 80), recordDate: date, frozenLatex: quantity, latexThread: quantity });
const teamExportRow = z.object({ unit: text("Đội", 120), periodLabel: text("Đợt", 80), recordDate: date, frozenContaminatedLatex: quantity, latexThread: quantity });
const workerPlotAllocationRow = z.object({ unit: text("Đội", 120), workerName: text("Nhân công", 160), employeeCode: z.string().max(64).optional().nullable(), gardenType: z.enum(["A", "B", "C"]), plotCode: text("Mã lô", 48), rowStart: z.coerce.number().int().positive("Hàng từ phải lớn hơn 0").max(99999), rowEnd: z.coerce.number().int().positive("Hàng đến phải lớn hơn 0").max(99999), areaHa: z.coerce.number().positive("Diện tích phải lớn hơn 0").max(999999) }).refine(row => row.rowStart <= row.rowEnd, { message: "Hàng từ phải nhỏ hơn hoặc bằng Hàng đến" });

export const dataToolsRouter = router({
  summary: protectedProcedure.query(async ({ ctx }) => { const profile = await requirePermission(ctx, "dashboard:read"); if (profile.fullAccess || !profile.scopeUnits.length) return db.getExcelDataSummary(); const [imports, exports, plots, workers] = await Promise.all([db.listTeamImports(), db.listTeamExports(), db.listPlots(), db.listWorkers()]); const scopedImports = filterByScope(imports, profile); const scopedExports = filterByScope(exports, profile); return { plots: filterByScope(plots, profile).length, workers: workers.filter(row => row.unit && profile.scopeUnits.includes(row.unit)).length, teamImports: scopedImports.length, teamExports: scopedExports.length, totalImport: scopedImports.reduce((sum, row) => sum + row.totalImport, 0), totalExport: scopedExports.reduce((sum, row) => sum + row.totalExport, 0) }; }),
  teamImports: protectedProcedure.query(async ({ ctx }) => filterByScope(await db.listTeamImports(), await requirePermission(ctx, "reports:read"))),
  teamExports: protectedProcedure.query(async ({ ctx }) => filterByScope(await db.listTeamExports(), await requirePermission(ctx, "reports:read"))),
  workerPlotAllocations: protectedProcedure.query(async ({ ctx }) => filterByScope(await db.listWorkerPlotAllocations(), await requirePermission(ctx, "reports:read"))),
  backups: router({
    list: adminProcedure.query(() => db.listDataBackups()),
    create: adminProcedure.mutation(async ({ ctx }) => {
      const created = await db.createDataBackup({ backupKey: `manual-${Date.now()}-${ctx.user.id}`, source: "manual", createdBy: ctx.user.id });
      await db.logActivity(ctx.user.id, { eventType: "data.backup.manual", entityType: "data_backup", entityId: created.id, summary: `Tạo bản sao lưu dữ liệu ${created.fileName}`, metadata: { recordCount: created.recordCount, source: created.source } });
      return created;
    }),
    download: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => db.getDataBackupDownload(input.id)),
  }),
  warehouseLoss: protectedProcedure.input(z.object({ periodLabel: z.string().trim().max(80).optional(), monthLabel: z.string().trim().max(16).optional() }).optional()).query(async ({ input, ctx }) => { const profile = await requirePermission(ctx, "warehouse:read"); if (profile.fullAccess || !profile.scopeUnits.length) return db.getWarehouseLossByTeam(input?.periodLabel, input?.monthLabel); const [imports, exports] = await Promise.all([db.listTeamImports(), db.listTeamExports()]); const { aggregateWarehouseLoss } = await import("../warehouseLossMath"); return aggregateWarehouseLoss(filterByScope(imports, profile), filterByScope(exports, profile), input?.periodLabel, input?.monthLabel); }),
  import: router({
    plots: adminProcedure.input(z.object({ rows: z.array(plotRow).min(1).max(1000) })).mutation(async ({ input, ctx }) => { await db.bulkUpsertExcelPlots(input.rows, ctx.user.id); await db.logActivity(ctx.user.id, { eventType: "excel.import", entityType: "plots", summary: `Import ${input.rows.length} vườn/lô từ Excel`, metadata: { count: input.rows.length } }); return { success: true, imported: input.rows.length }; }),
    workers: adminProcedure.input(z.object({ rows: z.array(workerRow).min(1).max(2000) })).mutation(async ({ input, ctx }) => { await db.bulkUpsertExcelWorkers(input.rows, ctx.user.id); await db.logActivity(ctx.user.id, { eventType: "excel.import", entityType: "workers", summary: `Import ${input.rows.length} nhân công từ Excel`, metadata: { count: input.rows.length } }); return { success: true, imported: input.rows.length }; }),
    workerCodes: adminProcedure.input(z.object({ rows: z.array(workerCodeRow).min(1).max(2000) })).mutation(async ({ input, ctx }) => { const updated = await db.bulkUpdateWorkerCodes(input.rows); await db.logActivity(ctx.user.id, { eventType: "excel.import", entityType: "worker_codes", summary: `Cập nhật ${updated} mã số nhân công từ Excel`, metadata: { count: updated } }); return { success: true, updated }; }),
    plotIndicators: adminProcedure.input(z.object({ rows: z.array(plotIndicatorRow).min(1).max(1000) })).mutation(async ({ input, ctx }) => { const updated = await db.bulkUpdatePlotIndicators(input.rows); await db.logActivity(ctx.user.id, { eventType: "excel.import", entityType: "plot_indicators", summary: `Cập nhật định kỳ chỉ số cây cho ${updated} lô từ Excel`, metadata: { count: updated } }); return { success: true, updated }; }),
    teamImports: adminProcedure.input(z.object({ rows: z.array(teamImportRow).min(1).max(2000) })).mutation(async ({ input, ctx }) => { await db.bulkUpsertTeamImports(input.rows, ctx.user.id); await db.logActivity(ctx.user.id, { eventType: "excel.import", entityType: "team_imports", summary: `Import ${input.rows.length} dòng nhập mủ từ Excel`, metadata: { count: input.rows.length } }); return { success: true, imported: input.rows.length }; }),
    teamExports: adminProcedure.input(z.object({ rows: z.array(teamExportRow).min(1).max(2000) })).mutation(async ({ input, ctx }) => { await db.bulkUpsertTeamExports(input.rows, ctx.user.id); await db.logActivity(ctx.user.id, { eventType: "excel.import", entityType: "team_exports", summary: `Import ${input.rows.length} dòng xuất mủ từ Excel`, metadata: { count: input.rows.length } }); return { success: true, imported: input.rows.length }; }),
    workerPlotAllocations: adminProcedure.input(z.object({ rows: z.array(workerPlotAllocationRow).min(1).max(5000) })).mutation(async ({ input, ctx }) => { const imported = await db.bulkUpsertWorkerPlotAllocations(input.rows, ctx.user.id); await db.logActivity(ctx.user.id, { eventType: "excel.import", entityType: "worker_plot_allocations", summary: `Import ${imported} dòng phân chia nhân công vườn cây`, metadata: { count: imported, units: Array.from(new Set(input.rows.map(row => row.unit))) } }); return { success: true, imported }; }),
  }),
});
