import { TRPCError } from "@trpc/server";
import { z } from "zod";
import * as db from "../db";
import { clearInternalSessionCookie, hashPassword, internalSessionCookie, sessionToken, verifyPassword } from "../internalAuth";
import { adminProcedure, publicProcedure, router } from "../_core/trpc";

const groupType = z.enum(["board", "functional", "production"]);
const accountInput = z.object({ username: z.string().trim().toLowerCase().min(3).max(64).regex(/^[a-z0-9._-]+$/, "Tên đăng nhập chỉ gồm chữ thường, số, dấu chấm, gạch dưới hoặc gạch ngang"), password: z.string().min(8).max(128), displayName: z.string().trim().min(2).max(160), groupType, roleCode: z.string().trim().min(2).max(64), scopeUnits: z.array(z.string().trim().min(1).max(120)).max(30), permissions: z.array(z.string().trim().min(1).max(80)).max(30), active: z.boolean().optional() });

export const internalAccountsRouter = router({
  login: publicProcedure.input(z.object({ username: z.string().trim().toLowerCase(), password: z.string().min(1) })).mutation(async ({ input, ctx }) => { const account = await db.getInternalAccountByUsername(input.username); if (!account || account.isActive !== 1 || !verifyPassword(input.password, account.passwordHash)) throw new TRPCError({ code: "UNAUTHORIZED", message: "Tên đăng nhập hoặc mật khẩu không đúng" }); const cookie = internalSessionCookie(sessionToken(account.userId)); ctx.res.cookie(cookie.name, cookie.value, cookie.options); await db.logActivity(account.userId, { eventType: "auth.login", entityType: "session", summary: "Đăng nhập hệ thống" }); return { success: true, displayName: account.displayName }; }),
  logout: publicProcedure.mutation(({ ctx }) => { const cookie = clearInternalSessionCookie(); ctx.res.clearCookie(cookie.name, cookie.options); return { success: true }; }),
  list: adminProcedure.query(() => db.listInternalAccounts()),
  create: adminProcedure.input(accountInput).mutation(async ({ input, ctx }) => { const exists = await db.getInternalAccountByUsername(input.username); if (exists) throw new TRPCError({ code: "CONFLICT", message: "Tên đăng nhập đã tồn tại" }); const created = await db.createInternalAccount(input, hashPassword(input.password), ctx.user.id); await db.logActivity(ctx.user.id, { eventType: "account.create", entityType: "internal_account", entityId: created.userId, summary: `Cấp tài khoản ${input.username}`, metadata: { groupType: input.groupType, roleCode: input.roleCode, scopeUnits: input.scopeUnits } }); return { success: true }; }),
  update: adminProcedure.input(z.object({ id: z.number().int().positive(), displayName: z.string().trim().min(2).max(160).optional(), groupType: groupType.optional(), roleCode: z.string().trim().min(2).max(64).optional(), scopeUnits: z.array(z.string().trim().min(1).max(120)).max(30).optional(), permissions: z.array(z.string().trim().min(1).max(80)).max(30).optional(), active: z.boolean().optional(), password: z.string().min(8).max(128).optional() })).mutation(async ({ input, ctx }) => { const { id, password, ...values } = input; await db.updateInternalAccount(id, { ...values, passwordHash: password ? hashPassword(password) : undefined }); await db.logActivity(ctx.user.id, { eventType: "account.update", entityType: "internal_account", entityId: id, summary: "Cập nhật quyền hoặc trạng thái tài khoản", metadata: { changed: Object.keys(values), passwordChanged: Boolean(password) } }); return { success: true }; }),
});
