import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader, Panel } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { ClipboardList, LogIn, RefreshCw, ShieldAlert, UserCog } from "lucide-react";
import { useMemo, useState } from "react";

const eventLabel: Record<string, string> = { "auth.login": "Đăng nhập", "account.create": "Cấp tài khoản", "account.update": "Cập nhật tài khoản", "plot.create": "Tạo vườn", "plot.remove": "Xóa vườn", "latex.import.save": "Nhập mủ", "latex.export.save": "Xuất mủ", "care.create": "Nhật ký chăm sóc", "operations.save": "Khai thác & chăm sóc", "worker.create": "Tạo nhân công", "assignment.create": "Phân công" };
const iconFor = (event: string) => event === "auth.login" ? LogIn : event.startsWith("account") ? UserCog : ClipboardList;

export default function ActivityLogPage() {
  const { user } = useAuth(); const initialFilters = useMemo(() => new URLSearchParams(window.location.search), []); const [eventType, setEventType] = useState(() => initialFilters.get("event") ?? "all"); const [username, setUsername] = useState(() => initialFilters.get("account") ?? "all"); const [startDate, setStartDate] = useState(() => initialFilters.get("from") ?? ""); const [endDate, setEndDate] = useState(() => initialFilters.get("to") ?? ""); const [keyword, setKeyword] = useState(() => initialFilters.get("q") ?? "");
  const filters = useMemo(() => ({ ...(eventType === "all" ? {} : { eventType }), ...(username === "all" ? {} : { username }), ...(startDate ? { startDate } : {}), ...(endDate ? { endDate } : {}), limit: 300 }), [endDate, eventType, startDate, username]);
  const query = trpc.activity.list.useQuery(filters);
  const accounts = trpc.activity.accounts.useQuery();
  const events = useMemo(() => Array.from(new Set((query.data ?? []).map(row => row.eventType))), [query.data]);
  const rows = useMemo(() => (query.data ?? []).filter(row => !keyword || [row.username, row.displayName, row.summary].some(value => value?.toLowerCase().includes(keyword.toLowerCase()))), [query.data, keyword]);
  if (user?.role !== "admin") return <div className="page-enter"><PageHeader eyebrow="Quản trị hệ thống" title="Nhật ký hoạt động" description="Chỉ quản trị viên được phép xem lịch sử hệ thống." /><Panel title="Không có quyền truy cập"><div className="flex items-center gap-3 text-rose-700"><ShieldAlert className="h-5 w-5" />Trang này chỉ dành cho admin.</div></Panel></div>;
  return <div className="page-enter"><PageHeader eyebrow="Quản trị hệ thống" title="Nhật ký hoạt động" description="Theo dõi đăng nhập và các thao tác chỉnh sửa dữ liệu theo từng tài khoản." action={<Button variant="outline" onClick={() => { query.refetch(); accounts.refetch(); }}><RefreshCw className="mr-2 h-4 w-4" />Làm mới</Button>} /><Panel title="Lịch sử hệ thống" description="Lưu tối đa 300 sự kiện mới nhất. Mật khẩu và dữ liệu nhạy cảm không được ghi vào nhật ký."><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select value={eventType} onValueChange={setEventType}><SelectTrigger><SelectValue placeholder="Tất cả sự kiện" /></SelectTrigger><SelectContent><SelectItem value="all">Tất cả sự kiện</SelectItem>{events.map(event => <SelectItem key={event} value={event}>{eventLabel[event] ?? event}</SelectItem>)}</SelectContent></Select><Select value={username} onValueChange={setUsername}><SelectTrigger><SelectValue placeholder="Tất cả tài khoản" /></SelectTrigger><SelectContent><SelectItem value="all">Tất cả tài khoản</SelectItem>{(accounts.data ?? []).map(account => <SelectItem key={account.username} value={account.username}>{account.displayName} · @{account.username}</SelectItem>)}</SelectContent></Select><Input type="date" aria-label="Từ ngày" value={startDate} onChange={event => setStartDate(event.target.value)} /><Input type="date" aria-label="Đến ngày" value={endDate} onChange={event => setEndDate(event.target.value)} /></div><Input className="mb-4" value={keyword} onChange={event => setKeyword(event.target.value)} placeholder="Tìm tài khoản hoặc nội dung thao tác" />{query.isLoading ? <div className="space-y-3">{[1, 2, 3, 4].map(item => <div key={item} className="h-16 animate-pulse rounded-xl bg-slate-100" />)}</div> : query.error ? <p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">Chỉ admin được phép truy cập nhật ký hoạt động.</p> : <div className="space-y-2">{rows.map(row => { const Icon = iconFor(row.eventType); return <div key={row.id} className="flex gap-3 rounded-xl border border-slate-100 bg-white p-3.5"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-1"><p className="text-sm font-semibold text-slate-900">{eventLabel[row.eventType] ?? row.eventType}</p><time className="text-xs text-slate-400">{new Date(row.createdAt).toLocaleString("vi-VN")}</time></div><p className="mt-1 text-sm text-slate-600">{row.summary}</p><p className="mt-1 text-xs text-slate-400">{row.displayName || "Hệ thống"}{row.username ? ` · @${row.username}` : ""}{row.entityId ? ` · #${row.entityId}` : ""}</p></div></div>; })}{!rows.length ? <div className="py-14 text-center text-sm text-slate-500">Chưa có sự kiện phù hợp. Các lần đăng nhập và thao tác tiếp theo sẽ xuất hiện tại đây.</div> : null}</div>}</Panel></div>;
}
