import { EmptyState, PageHeader, Panel } from "@/components/PageHeader";
import { QueryError } from "@/components/QueryError";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { buildGardenAreaChartData } from "@/lib/gardenAreaChart";
import { currentPeriod, formatAreaHa, formatPercent } from "@/lib/rubber";
import { trpc } from "@/lib/trpc";
import { TEAM_ORDER } from "@shared/teamOrder";
import { ArrowDownToLine, ArrowUpFromLine, BarChart3, Building2, CalendarDays, ChartNoAxesCombined, Download, Eye, EyeOff, MapPinned, TrendingDown, TrendingUp, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";

const monthlyConfig = { production: { label: "Sản lượng", color: "#059669" } };
const periodConfig = { production: { label: "Sản lượng", color: "#0f766e" } };
const teamChartConfig = Object.fromEntries(TEAM_ORDER.map((unit, index) => [`team${index + 1}`, { label: unit, color: ["#047857", "#0d9488", "#0284c7", "#7c3aed", "#ea580c", "#be123c"][index] }])) as Record<string, { label: string; color: string }>;
const workforceTrendConfig = { activeCount: { label: "Nhân công hoạt động", color: "#7c3aed" } };
const gardenAreaConfig = { gardenA: { label: "Vườn A", color: "#059669" }, gardenB: { label: "Vườn B", color: "#0284c7" }, gardenC: { label: "Vườn C", color: "#d97706" } };

function exactNumber(value: number) { return new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 8 }).format(value); }

export default function Home() {
  const [, navigate] = useLocation();
  const { data: periods = [] } = trpc.rubber.periods.useQuery();
  const [periodLabel, setPeriodLabel] = useState<string>(currentPeriod());
  const [productionYear, setProductionYear] = useState<number | undefined>();
  const [productionMonth, setProductionMonth] = useState<number | undefined>();
  const [productionUnit, setProductionUnit] = useState("all");
  const [workforceUnit, setWorkforceUnit] = useState("all");
  const [visibleColumns, setVisibleColumns] = useState({ area: true, plots: true, workforce: true, production: true });
  const [preferencesHydrated, setPreferencesHydrated] = useState(false);
  const { data: dashboard, isLoading, error: dashboardError } = trpc.rubber.dashboard.useQuery({ periodLabel });
  const { data: productionManagement } = trpc.rubber.latexProductionManagement.useQuery({ year: productionYear, month: productionMonth, unit: productionUnit === "all" ? undefined : productionUnit });
  const { data: dashboardPreferences } = trpc.rubber.dashboardPreferences.get.useQuery();
  const saveDashboardPreferences = trpc.rubber.dashboardPreferences.save.useMutation();
  const { data: plots = [] } = trpc.rubber.plots.list.useQuery();
  const { data: imports, error: importsError } = trpc.rubber.imports.list.useQuery();
  const { data: exports, error: exportsError } = trpc.rubber.exports.list.useQuery();
  const summary = dashboard ?? { plotCount: 0, totalArea: 0, totalProduction: 0, workforceCount: 0, workforceSummary: { staffingTarget: 0, currentCount: 0, shortageCount: 0, surplusCount: 0 }, workforceTeams: [], workforceTrend: [], totalImport: 0, totalExport: 0, lossRate: 0, managementGroups: [], periodProduction: [], monthlyProduction: [], teamOverview: [], teamMonthlyProduction: [], teamQuarterlyProduction: [], quarterlyYearComparison: null };
  const managementSummary = useMemo(() => summary.managementGroups.reduce((sum: { staffingTarget: number; currentCount: number; shortageCount: number; surplusCount: number }, group: { staffingTarget: number | null; currentCount: number; shortageCount: number | null; surplusCount: number | null }) => ({ staffingTarget: sum.staffingTarget + (group.staffingTarget ?? 0), currentCount: sum.currentCount + group.currentCount, shortageCount: sum.shortageCount + (group.shortageCount ?? 0), surplusCount: sum.surplusCount + (group.surplusCount ?? 0) }), { staffingTarget: 0, currentCount: 0, shortageCount: 0, surplusCount: 0 }), [summary.managementGroups]);
  const workforceTotal = {
    staffingTarget: managementSummary.staffingTarget + summary.workforceSummary.staffingTarget,
    currentCount: managementSummary.currentCount + summary.workforceSummary.currentCount,
    shortageCount: managementSummary.shortageCount + summary.workforceSummary.shortageCount,
    surplusCount: managementSummary.surplusCount + summary.workforceSummary.surplusCount,
  };
  const teamMonthlyChartData = useMemo(() => summary.teamMonthlyProduction.map((row: Record<string, string | number>) => Object.fromEntries([["month", row.month], ...TEAM_ORDER.map((unit, index) => [`team${index + 1}`, Number(row[unit] ?? 0)])])), [summary.teamMonthlyProduction]);
  const teamQuarterlyChartData = useMemo(() => summary.teamQuarterlyProduction.map((row: Record<string, string | number>) => Object.fromEntries([["quarter", row.quarter], ...TEAM_ORDER.map((unit, index) => [`team${index + 1}`, Number(row[unit] ?? 0)])])), [summary.teamQuarterlyProduction]);
  const quarterlyYearComparison = (dashboard as { quarterlyYearComparison?: { currentLabel: string; previousLabel: string; hasPreviousData: boolean; teams: { unit: string; currentTotalImport: number; previousTotalImport: number | null; importChange: number | null; changePercent: number | null }[] } } | undefined)?.quarterlyYearComparison ?? null;
  const quarterlyYearChartData = useMemo(() => quarterlyYearComparison?.teams.map((team: { unit: string; currentTotalImport: number; previousTotalImport: number | null }) => ({ unit: team.unit, current: team.currentTotalImport, previous: team.previousTotalImport ?? 0 })) ?? [], [quarterlyYearComparison]);
  useEffect(() => { if (!productionYear && productionManagement?.year) setProductionYear(productionManagement.year); if (!productionMonth && productionManagement?.month) setProductionMonth(productionManagement.month); }, [productionYear, productionMonth, productionManagement?.year, productionManagement?.month]);
  const production = productionManagement ?? { year: productionYear ?? new Date().getFullYear(), month: productionMonth ?? new Date().getMonth() + 1, unit: productionUnit, availableYears: [productionYear ?? new Date().getFullYear()], availableMonths: [productionMonth ?? new Date().getMonth() + 1], availableUnits: TEAM_ORDER, frozenLatex: 0, latexThread: 0, totalImport: 0, previousMonth: 0, previousYear: 0, previousTotalImport: 0, importChange: 0, importRecordCount: 0, exportRecordCount: 0, teamComparisons: [] as { unit: string; currentTotalImport: number; previousTotalImport: number; importChange: number; changePercent: number | null }[] };
  const selectedWorkforce = workforceUnit === "all" ? summary.workforceSummary : summary.workforceTeams.find((team: { unit: string }) => team.unit === workforceUnit) ?? summary.workforceSummary;
  const exportProductionExcel = async () => { const XLSX = await import("xlsx"); const details = [{ "Năm": production.year, "Tháng": production.month, "Đội": productionUnit === "all" ? "Tất cả đội sản xuất" : productionUnit, "Mủ đông, tạp nhập (kg)": production.frozenLatex, "Mủ dây nhập (kg)": production.latexThread, "Tổng nhập (kg)": production.totalImport, "Tổng nhập tháng trước (kg)": production.previousTotalImport, "Chênh lệch tháng trước (kg)": production.importChange, "Số bản ghi nhập": production.importRecordCount, "Số bản ghi xuất": production.exportRecordCount }]; const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(details), "Sản lượng mủ"); XLSX.writeFile(workbook, `quan-ly-san-luong-${production.year}-${String(production.month).padStart(2, "0")}.xlsx`); };
  const comparisonPercent = production.previousTotalImport > 0 ? (production.importChange / production.previousTotalImport) * 100 : null;
  const workforceTrendData = summary.workforceTrend.map((point: { month: string; activeCount: number; totalCount: number }) => ({ ...point, label: `${point.month.slice(5, 7)}/${point.month.slice(0, 4)}` }));
  const gardenAreaChartData = useMemo(() => buildGardenAreaChartData(plots), [plots]);
  const hasGardenAreaData = gardenAreaChartData.some(row => row.gardenA + row.gardenB + row.gardenC > 0);
  useEffect(() => { if (dashboardPreferences && !preferencesHydrated) { setVisibleColumns(dashboardPreferences.teamOverviewColumns); setPreferencesHydrated(true); } }, [dashboardPreferences, preferencesHydrated]);
  const toggleColumn = (column: keyof typeof visibleColumns) => { const next = { ...visibleColumns, [column]: !visibleColumns[column] }; setVisibleColumns(next); saveDashboardPreferences.mutate({ teamOverviewColumns: next }); };

  return <div className="page-enter">
    <PageHeader eyebrow="Trung tâm điều hành" title="Tổng quan vận hành" description="Theo dõi diện tích, nguồn lực và sản lượng theo kỳ, tháng và sáu đội." action={<label className="flex w-full items-center justify-between gap-2 rounded-full bg-emerald-100 px-4 py-2 text-base font-semibold text-emerald-900 sm:w-auto sm:px-3 sm:py-1.5 sm:text-sm">Kỳ xem<select value={periodLabel} onChange={event => setPeriodLabel(event.target.value)} className="min-w-0 bg-transparent text-right text-emerald-900 outline-none">{Array.from(new Set([periodLabel, ...periods])).map(period => <option key={period} value={period}>{period}</option>)}</select></label>} />
    {dashboardError || importsError || exportsError ? <div className="mb-5"><QueryError message={dashboardError?.message || importsError?.message || exportsError?.message} /></div> : null}

    <div className="grid grid-cols-2 gap-3 md:grid-cols-2 xl:grid-cols-4">
      <MetricCard icon={MapPinned} label="Tổng diện tích" value={`${formatAreaHa(summary.totalArea)} ha`} help="Từ các lô đang quản lý" tone="emerald" loading={isLoading} />
      <MetricCard icon={Building2} label="Tổng vườn" value={exactNumber(summary.plotCount)} help="Số lô/vườn đang quản lý" tone="sky" loading={isLoading} />
      <MetricCard icon={ChartNoAxesCombined} label="Tổng sản lượng" value={`${exactNumber(summary.totalProduction)} kg`} help="Tổng cộng nhập mọi kỳ" tone="amber" loading={isLoading} />
      <MetricCard icon={UsersRound} label="Nhân công hoạt động" value={exactNumber(summary.workforceCount)} help="Nhân công đang làm việc" tone="violet" loading={isLoading} />
    </div>

    <div className="mt-5"><Panel title="Quản lý sản lượng mủ" description="Theo dõi mủ đông tạp và mủ dây theo tháng, năm, toàn bộ hoặc từng đội sản xuất.">
      <div className="mt-1 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap sm:items-center"><label className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-emerald-800"><CalendarDays className="h-4 w-4 shrink-0" /><select aria-label="Tháng" value={production.month} onChange={event => setProductionMonth(Number(event.target.value))} className="min-w-0 bg-transparent outline-none">{production.availableMonths.map(month => <option key={month} value={month}>Tháng {month}</option>)}</select></label><select aria-label="Năm" value={production.year} onChange={event => { setProductionYear(Number(event.target.value)); setProductionMonth(undefined); }} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700 outline-none">{production.availableYears.map(year => <option key={year} value={year}>Năm {year}</option>)}</select><select aria-label="Đội sản xuất" value={productionUnit} onChange={event => setProductionUnit(event.target.value)} className="col-span-2 h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700 outline-none sm:col-span-1"><option value="all">Tất cả đội sản xuất</option>{production.availableUnits.map(unit => <option key={unit} value={unit}>{unit}</option>)}</select></div><Button size="sm" onClick={exportProductionExcel} className="w-full bg-emerald-700 hover:bg-emerald-800 lg:w-auto"><Download className="mr-2 h-4 w-4" />Xuất Excel</Button></div>
      <div className="mt-4 grid grid-cols-3 gap-2 sm:gap-3"><ProductionMetric label="Mủ đông, tạp nhập" value={production.frozenLatex} /><ProductionMetric label="Mủ dây nhập" value={production.latexThread} /><ProductionMetric label="Tổng nhập" value={production.totalImport} strong /></div>
      <div className={`mt-3 flex items-center gap-2 rounded-xl border px-3 py-2 text-sm ${production.importChange >= 0 ? "border-emerald-100 bg-emerald-50 text-emerald-800" : "border-amber-100 bg-amber-50 text-amber-800"}`}>{production.importChange >= 0 ? <TrendingUp className="h-4 w-4 shrink-0" /> : <TrendingDown className="h-4 w-4 shrink-0" />}<span>So với tháng {production.previousMonth}/{production.previousYear}: <strong>{production.importChange >= 0 ? "+" : ""}{exactNumber(production.importChange)} kg</strong>{comparisonPercent != null ? ` (${production.importChange >= 0 ? "+" : ""}${formatPercent(comparisonPercent)})` : ""}</span></div>
      {!productionUnit || productionUnit === "all" ? <div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{production.teamComparisons.map(team => <TeamComparison key={team.unit} {...team} previousMonth={production.previousMonth} previousYear={production.previousYear} />)}</div> : null}
      <p className="mt-4 text-sm text-slate-500">Đang xem: <span className="font-semibold text-slate-700">{productionUnit === "all" ? "toàn bộ đội sản xuất" : productionUnit}</span> · Nhập {production.importRecordCount} bản ghi · Xuất {production.exportRecordCount} bản ghi</p>
    </Panel></div>

    <div className="mt-5 grid gap-5 xl:grid-cols-[0.95fr_1.05fr]">
      <Panel title="Tổng Quản lý và nhân công" description="Bao gồm Đội ngũ quản lý và nhân công sản xuất; thừa/thiếu tính theo chỉ tiêu đã nhập.">
        <div className="grid gap-3 sm:grid-cols-2"><StaffingBlock title="Đội ngũ quản lý" target={managementSummary.staffingTarget} current={managementSummary.currentCount} shortage={managementSummary.shortageCount} surplus={managementSummary.surplusCount} /><StaffingBlock title="Nhân công 6 đội" target={selectedWorkforce.staffingTarget} current={selectedWorkforce.currentCount} shortage={selectedWorkforce.shortageCount} surplus={selectedWorkforce.surplusCount} action={<select aria-label="Chọn đội nhân công" value={workforceUnit} onChange={event => setWorkforceUnit(event.target.value)} className="mt-2 h-8 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs font-semibold text-slate-700 outline-none"><option value="all">Tất cả 6 đội</option>{summary.workforceTeams.map((team: { unit: string }) => <option key={team.unit} value={team.unit}>{team.unit}</option>)}</select>} /></div>
        <div className="mt-3 rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-sm font-semibold text-emerald-900">Tổng quản lý và nhân công</p><div className="mt-3 grid grid-cols-4 gap-2"><MiniMetric label="Biên chế" value={workforceTotal.staffingTarget || "—"} /><MiniMetric label="Hiện có" value={workforceTotal.currentCount} /><MiniMetric label="Thừa" value={workforceTotal.surplusCount} /><MiniMetric label="Thiếu" value={workforceTotal.shortageCount} /></div></div>
        <ChartPanel title="Xu hướng biến động nhân công theo tháng" empty={!workforceTrendData.length}><ChartContainer config={workforceTrendConfig} className="h-44 w-full"><LineChart data={workforceTrendData}><CartesianGrid vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} width={42} /><ChartTooltip content={<ChartTooltipContent formatter={(value) => `${exactNumber(Number(value))} người`} />} /><Line type="monotone" dataKey="activeCount" name="activeCount" stroke="var(--color-activeCount)" strokeWidth={2.5} dot={{ r: 4 }} /></LineChart></ChartContainer></ChartPanel>
      </Panel>
      <Panel title="Phân tích sản lượng" description={`Sản lượng tổng và diễn biến ${periodLabel} đang xem; giá trị giữ nguyên độ chính xác dữ liệu nguồn.`}>
        <div className="grid gap-3 sm:grid-cols-2"><SummaryBlock label="Sản lượng tổng" value={summary.totalProduction} accent="text-emerald-700" /><SummaryBlock label={`Sản lượng ${periodLabel}`} value={summary.totalImport} accent="text-sky-700" /></div>
        <ChartPanel title={`Sản lượng theo tháng · ${periodLabel}`} empty={!summary.monthlyProduction.length}><ChartContainer config={monthlyConfig} className="h-56 w-full"><LineChart data={summary.monthlyProduction}><CartesianGrid vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} /><YAxis tickFormatter={exactNumber} width={64} /><ChartTooltip content={<ChartTooltipContent formatter={(value) => `${exactNumber(Number(value))} kg`} />} /><Line type="monotone" dataKey="value" name="production" stroke="var(--color-production)" strokeWidth={2.5} dot={{ r: 3 }} /></LineChart></ChartContainer></ChartPanel>
      </Panel>
    </div>

    <div className="mt-5 grid gap-5 xl:grid-cols-[0.85fr_1.15fr]">
      <Panel title="Sản lượng từng kỳ" description="Tổng cộng nhập theo từng kỳ vận hành."><ChartPanel empty={!summary.periodProduction.length}><ChartContainer config={periodConfig} className="h-64 w-full"><BarChart data={summary.periodProduction}><CartesianGrid vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} /><YAxis tickFormatter={exactNumber} width={64} /><ChartTooltip content={<ChartTooltipContent formatter={(value) => `${exactNumber(Number(value))} kg`} />} /><Bar dataKey="value" name="production" fill="var(--color-production)" radius={[6, 6, 0, 0]} /></BarChart></ChartContainer></ChartPanel></Panel>
      <Panel title="Tổng quan theo 6 đội" description={`Diện tích, số lô, nhân công và sản lượng ${periodLabel}; dữ liệu tháng hiển thị trong biểu đồ.`}>
        <details className="mb-3 hidden rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 sm:block"><summary className="flex cursor-pointer items-center gap-2 text-sm font-semibold text-slate-700"><Eye className="h-4 w-4 text-emerald-700" />Tùy chỉnh cột hiển thị</summary><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2">{([{ key: "area", label: "Diện tích" }, { key: "plots", label: "Số lô" }, { key: "workforce", label: "Nhân công" }, { key: "production", label: "Tổng sản lượng" }] as const).map(column => <label key={column.key} className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={visibleColumns[column.key]} onChange={() => toggleColumn(column.key)} />{column.label}</label>)}</div></details>
        <div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-slate-200 text-xs font-bold uppercase tracking-[0.1em] text-slate-400"><th className="px-3 py-4">Đội</th>{visibleColumns.area ? <th className="px-3 py-4 text-right">Diện tích</th> : null}{visibleColumns.plots ? <th className="px-3 py-4 text-right">Số lô</th> : null}{visibleColumns.workforce ? <th className="px-3 py-4 text-right">Nhân công</th> : null}{visibleColumns.production ? <th className="px-3 py-4 text-right">Tổng sản lượng</th> : null}</tr></thead><tbody>{summary.teamOverview.map((team: { unit: string; areaHa: number; plotCount: number; workforceCount: number; totalProduction: number }) => <tr key={team.unit} className="border-b border-slate-100 last:border-0"><td className="px-3 py-4 font-semibold text-slate-800">{team.unit}</td>{visibleColumns.area ? <td className="px-3 py-4 text-right">{formatAreaHa(team.areaHa)} ha</td> : null}{visibleColumns.plots ? <td className="px-3 py-4 text-right">{exactNumber(team.plotCount)}</td> : null}{visibleColumns.workforce ? <td className="px-3 py-4 text-right">{exactNumber(team.workforceCount)}</td> : null}{visibleColumns.production ? <td className="px-3 py-4 text-right font-semibold text-emerald-700">{exactNumber(team.totalProduction)} kg</td> : null}</tr>)}</tbody></table></div>
        <div className="space-y-2 sm:hidden">{summary.teamOverview.map((team: { unit: string; areaHa: number; plotCount: number; workforceCount: number; totalProduction: number }) => <div key={team.unit} className="rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="flex items-center justify-between"><p className="font-semibold text-slate-900">{team.unit}</p><p className="font-semibold text-emerald-700">{exactNumber(team.totalProduction)} kg</p></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><TeamCell label="Diện tích" value={`${formatAreaHa(team.areaHa)} ha`} /><TeamCell label="Số lô" value={exactNumber(team.plotCount)} /><TeamCell label="Nhân công" value={exactNumber(team.workforceCount)} /></div></div>)}</div>
        <ChartPanel title={`Sản lượng theo tháng · ${periodLabel}`} empty={!teamMonthlyChartData.length}><ChartContainer config={teamChartConfig} className="h-64 w-full"><BarChart data={teamMonthlyChartData}><CartesianGrid vertical={false} /><XAxis dataKey="month" tickLine={false} axisLine={false} /><YAxis tickFormatter={exactNumber} width={64} /><ChartTooltip content={<ChartTooltipContent formatter={(value) => `${exactNumber(Number(value))} kg`} />} />{TEAM_ORDER.map((unit, index) => <Bar key={unit} dataKey={`team${index + 1}`} stackId="team" fill={`var(--color-team${index + 1})`} radius={[3, 3, 0, 0]} />)}</BarChart></ChartContainer></ChartPanel>
        <ChartPanel title="So sánh sản lượng theo quý · từng đội" empty={!teamQuarterlyChartData.length}><ChartContainer config={teamChartConfig} className="h-72 w-full"><BarChart data={teamQuarterlyChartData} barGap={2}><CartesianGrid vertical={false} /><XAxis dataKey="quarter" tickLine={false} axisLine={false} /><YAxis tickFormatter={exactNumber} width={64} /><ChartTooltip content={<ChartTooltipContent formatter={(value) => `${exactNumber(Number(value))} kg`} />} />{TEAM_ORDER.map((unit, index) => <Bar key={unit} dataKey={`team${index + 1}`} name={`team${index + 1}`} fill={`var(--color-team${index + 1})`} radius={[3, 3, 0, 0]} />)}</BarChart></ChartContainer></ChartPanel>
        <ChartPanel title={`So sánh ${quarterlyYearComparison?.currentLabel ?? "quý hiện tại"} với cùng kỳ năm trước`} empty={false}>
          {quarterlyYearComparison?.hasPreviousData ? <><ChartContainer config={{ current: { label: quarterlyYearComparison.currentLabel, color: "#047857" }, previous: { label: quarterlyYearComparison.previousLabel, color: "#94a3b8" } }} className="h-72 w-full"><BarChart data={quarterlyYearChartData} barGap={6}><CartesianGrid vertical={false} /><XAxis dataKey="unit" tickLine={false} axisLine={false} /><YAxis tickFormatter={exactNumber} width={64} /><ChartTooltip content={<ChartTooltipContent formatter={(value) => `${exactNumber(Number(value))} kg`} />} /><Bar dataKey="previous" name="previous" fill="var(--color-previous)" radius={[3, 3, 0, 0]} /><Bar dataKey="current" name="current" fill="var(--color-current)" radius={[3, 3, 0, 0]} /></BarChart></ChartContainer><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{quarterlyYearComparison.teams.map((team) => <div key={team.unit} className="rounded-lg border border-slate-100 bg-slate-50 p-3"><p className="font-semibold text-slate-900">{team.unit}</p><p className="mt-1 text-sm text-slate-600">{quarterlyYearComparison.currentLabel}: <strong>{exactNumber(team.currentTotalImport)} kg</strong></p><p className={`mt-1 text-sm font-semibold {(team.importChange ?? 0) >= 0 ? "text-emerald-700" : "text-amber-700"}`}>{quarterlyYearComparison.previousLabel}: {exactNumber(team.previousTotalImport ?? 0)} kg · {(team.importChange ?? 0) >= 0 ? "+" : ""}{exactNumber(team.importChange ?? 0)} kg{team.changePercent != null ? ` (${(team.importChange ?? 0) >= 0 ? "+" : ""}${formatPercent(team.changePercent)})` : ""}</p></div>)}</div></> : <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 px-4 py-6 text-sm text-slate-600">{quarterlyYearComparison ? `Chưa có dữ liệu ${quarterlyYearComparison.previousLabel}. Hãy nhập dữ liệu cùng kỳ để hệ thống so sánh theo từng đội.` : "Chưa có dữ liệu quý để so sánh."}</div>}
        </ChartPanel>
      </Panel>
    </div>

    <div className="mt-5"><Panel title="Diện tích Vườn A/B/C theo Đội" description="Tổng diện tích Lô đã phân loại theo từng Đội. Đơn vị tính: ha.">
      {hasGardenAreaData ? <><div className="mb-3 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-emerald-800">Vườn A</span><span className="rounded-full bg-sky-100 px-2.5 py-1 text-sky-800">Vườn B</span><span className="rounded-full bg-amber-100 px-2.5 py-1 text-amber-800">Vườn C</span></div><ChartContainer config={gardenAreaConfig} className="h-72 w-full"><BarChart data={gardenAreaChartData} barGap={6}><CartesianGrid vertical={false} /><XAxis dataKey="unit" tickLine={false} axisLine={false} /><YAxis tickFormatter={exactNumber} width={64} /><ChartTooltip content={<ChartTooltipContent formatter={(value) => `${exactNumber(Number(value))} ha`} />} /><Bar dataKey="gardenA" name="gardenA" fill="var(--color-gardenA)" radius={[3, 3, 0, 0]} /><Bar dataKey="gardenB" name="gardenB" fill="var(--color-gardenB)" radius={[3, 3, 0, 0]} /><Bar dataKey="gardenC" name="gardenC" fill="var(--color-gardenC)" radius={[3, 3, 0, 0]} /></BarChart></ChartContainer></> : <div className="grid h-48 place-items-center rounded-xl border border-dashed border-slate-200 bg-slate-50 px-5 text-center text-sm text-slate-500">Chưa có Lô được phân bổ vào Vườn A, B hoặc C. Hãy phân loại Lô trong Quản lý vườn để biểu đồ hiển thị diện tích thực tế.</div>}
    </Panel></div>

    <div className="mt-5"><Panel title="Tóm tắt nhập xuất mủ" description={`Diễn biến của ${periodLabel}. Hao kho được tính tự động trên cộng nhập.`}><div className="grid gap-3 sm:grid-cols-3"><SummaryBlock label="Cộng nhập" value={summary.totalImport} accent="text-emerald-700" /><SummaryBlock label="Cộng xuất" value={summary.totalExport} accent="text-sky-700" /><SummaryBlock label="Hao kho" value={summary.lossRate} suffix="%" accent={summary.lossRate > 5 ? "text-amber-700" : "text-emerald-700"} /></div><div className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-sm leading-6 text-slate-500"><span className="font-semibold text-slate-700">Công thức hao kho: </span>(cộng nhập − cộng xuất) / cộng nhập × 100%.</div><div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => navigate("/imports")} className="bg-emerald-700 hover:bg-emerald-800"><ArrowDownToLine className="mr-2 h-4 w-4" />Ghi nhận nhập mủ</Button><Button onClick={() => navigate("/exports")} variant="outline" className="bg-white"><ArrowUpFromLine className="mr-2 h-4 w-4" />Ghi nhận xuất mủ</Button></div></Panel></div>
    <div className="mt-5"><Panel title="Khởi động vận hành" description="Thiết lập dữ liệu theo thứ tự để báo cáo phản ánh chính xác."><div className="grid gap-3 md:grid-cols-3"><QuickAction step="01" title="Khai báo vườn" text="Bổ sung Đội, năm trồng, diện tích, ngày cạo và phân loại Vườn A/B/C." onClick={() => navigate("/plots")} /><QuickAction step="02" title="Ghi nhận mủ" text="Chọn đội, lô/vườn rồi nhập số liệu mủ theo ngày và đợt." onClick={() => navigate("/imports")} /><QuickAction step="03" title="Theo dõi báo cáo" text="Xem sản lượng, cộng nhập, cộng xuất, hao kho và tiến độ theo đội." onClick={() => navigate("/reports")} /></div></Panel></div>
    {!isLoading && summary.plotCount === 0 ? <div className="mt-5"><EmptyState title="Chưa có dữ liệu vườn" description="Bắt đầu bằng việc khai báo vườn để ghi nhận nhập mủ, xuất mủ và báo cáo tiến độ." /></div> : null}
  </div>;
}

function MetricCard({ icon: Icon, label, value, help, tone, loading }: { icon: typeof MapPinned; label: string; value: string; help: string; tone: "emerald" | "sky" | "amber" | "violet"; loading: boolean }) { const tones = { emerald: "bg-emerald-50 text-emerald-700", sky: "bg-sky-50 text-sky-700", amber: "bg-amber-50 text-amber-700", violet: "bg-violet-50 text-violet-700" }; return <Panel className="relative overflow-hidden p-4 sm:p-5"><div className={`mb-3 grid h-9 w-9 place-items-center rounded-xl ${tones[tone]}`}><Icon className="h-4 w-4 sm:h-5 sm:w-5" /></div><p className="text-xs font-medium text-slate-500 sm:text-sm">{label}</p><p className="font-display mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{loading ? "…" : value}</p><p className="mt-1 text-[10px] text-slate-400 sm:text-xs">{help}</p><div className="absolute -right-5 -top-6 h-24 w-24 rounded-full bg-slate-100/70" /></Panel>; }
function MiniMetric({ label, value }: { label: string; value: number | string }) { return <div className="rounded-lg bg-white p-2 text-center"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-semibold text-slate-900">{value}</p></div>; }
function TeamCell({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-semibold text-slate-800">{value}</p></div>; }
function TeamComparison({ unit, currentTotalImport, previousTotalImport, importChange, changePercent, previousMonth, previousYear }: { unit: string; currentTotalImport: number; previousTotalImport: number; importChange: number; changePercent: number | null; previousMonth: number; previousYear: number }) { const positive = importChange >= 0; return <div className={`rounded-xl border p-3 ${positive ? "border-emerald-100 bg-emerald-50/70" : "border-amber-100 bg-amber-50/70"}`}><div className="flex items-center justify-between gap-2"><p className="font-semibold text-slate-800">{unit}</p>{positive ? <TrendingUp className="h-4 w-4 text-emerald-700" /> : <TrendingDown className="h-4 w-4 text-amber-700" />}</div><p className="mt-2 text-lg font-bold text-slate-900">{exactNumber(currentTotalImport)} kg</p><p className="mt-1 text-xs text-slate-500">Tháng {previousMonth}/{previousYear}: {exactNumber(previousTotalImport)} kg</p><p className={`mt-1 text-sm font-semibold ${positive ? "text-emerald-700" : "text-amber-700"}`}>{positive ? "+" : ""}{exactNumber(importChange)} kg{changePercent != null ? ` (${positive ? "+" : ""}${formatPercent(changePercent)})` : ""}</p></div>; }
function StaffingBlock({ title, target, current, shortage, surplus, action }: { title: string; target: number; current: number; shortage: number; surplus: number; action?: React.ReactNode }) { return <div className="rounded-xl border border-slate-200 p-4"><p className="font-semibold text-slate-900">{title}</p>{action}<div className="mt-3 grid grid-cols-4 gap-2"><MiniMetric label="Biên chế" value={target || "—"} /><MiniMetric label="Hiện có" value={current} /><MiniMetric label="Thừa" value={surplus} /><MiniMetric label="Thiếu" value={shortage} /></div></div>; }
function ChartPanel({ title, empty, children }: { title?: string; empty: boolean; children: React.ReactNode }) { return <div className="mt-4"><p className="mb-2 text-sm font-semibold text-slate-700">{title}</p>{empty ? <div className="grid h-48 place-items-center rounded-xl border border-dashed border-slate-200 bg-slate-50 text-sm text-slate-500">Chưa có dữ liệu sản lượng cho phạm vi đã chọn.</div> : children}</div>; }
function SummaryBlock({ label, value, suffix = "kg", accent }: { label: string; value: number; suffix?: string; accent: string }) { return <div className="rounded-xl border border-slate-100 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">{label}</p><p className={`font-display mt-2 text-2xl font-bold ${accent}`}>{suffix === "%" ? formatPercent(value) : exactNumber(value)} <span className="text-sm font-semibold">{suffix}</span></p></div>; }
function ProductionMetric({ label, value, strong = false }: { label: string; value: number; strong?: boolean }) { return <div className={`rounded-xl p-3 sm:rounded-2xl sm:p-5 ${strong ? "bg-emerald-100" : "bg-emerald-50"}`}><p className="min-h-8 text-[11px] font-medium leading-4 text-slate-500 sm:min-h-0 sm:text-sm">{label}</p><p className="font-display mt-2 text-xl font-bold tracking-tight text-emerald-950 sm:mt-3 sm:text-3xl">{exactNumber(value)} <span className="text-xs sm:text-base">kg</span></p></div>; }
function QuickAction({ step, title, text, onClick }: { step: string; title: string; text: string; onClick: () => void }) { return <button onClick={onClick} className="group rounded-xl border border-slate-200 bg-slate-50/70 p-4 text-left transition hover:-translate-y-0.5 hover:border-emerald-200 hover:bg-emerald-50/60"><p className="text-xs font-bold tracking-[0.15em] text-emerald-700">{step}</p><p className="mt-3 font-display font-bold text-slate-900">{title}</p><p className="mt-1 text-sm leading-5 text-slate-500">{text}</p></button>; }
