import { describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "./_core/context";
const dbMocks = vi.hoisted(() => ({ saveDailyCareRecord: vi.fn(), logActivity: vi.fn(), listDailyCareRecords: vi.fn(), getProductionChangeReport: vi.fn(), getInternalAccountByUserId: vi.fn() }));
vi.mock("./db", () => dbMocks);
import { appRouter } from "./routers";
function context(role: "admin" | "user"): TrpcContext { return { user: { id: role === "admin" ? 1 : 2, openId: role, name: role, email: `${role}@example.com`, loginMethod: "manus", role, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { protocol: "https", headers: {} } as TrpcContext["req"], res: { clearCookie: vi.fn() } as unknown as TrpcContext["res"] }; }
const payload = { category: "tapping" as const, activityDate: new Date("2026-08-21T00:00:00.000Z"), unit: "Đội 1", gardenName: "Vườn A", workContent: "Cạo miệng mở", planQuantity: 57, actualQuantity: 57, metricUnit: "Vườn" };
describe("operationsRouter", () => {
  it("chỉ cho phép admin lưu nhật ký vận hành và ghi audit", async () => { dbMocks.getInternalAccountByUserId.mockResolvedValue(undefined); await expect(appRouter.createCaller(context("user")).operations.save(payload)).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(appRouter.createCaller(context("admin")).operations.save(payload)).resolves.toEqual({ success: true }); expect(dbMocks.saveDailyCareRecord).toHaveBeenCalledWith(expect.objectContaining({ workContent: "Cạo miệng mở" }), 1); expect(dbMocks.logActivity).toHaveBeenCalledWith(1, expect.objectContaining({ eventType: "operations.save" })); });
  it("chặn tài khoản chưa được cấp quyền và chỉ trả dữ liệu trong phạm vi Đội", async () => { dbMocks.getInternalAccountByUserId.mockResolvedValue(undefined); dbMocks.listDailyCareRecords.mockResolvedValue([]); await expect(appRouter.createCaller(context("user")).operations.list({ category: "care" })).rejects.toMatchObject({ code: "FORBIDDEN" }); dbMocks.getInternalAccountByUserId.mockResolvedValue({ isActive: 1, scopeUnits: JSON.stringify(["Đội 1"]), permissionProfile: JSON.stringify(["care:read"]) }); dbMocks.listDailyCareRecords.mockResolvedValue([{ unit: "Đội 1" }, { unit: "Đội 2" }]); await expect(appRouter.createCaller(context("user")).operations.list({ category: "care" })).resolves.toEqual([{ unit: "Đội 1" }]); expect(dbMocks.listDailyCareRecords).toHaveBeenCalledWith("care"); });
  it("chỉ cho phép đội ghi dữ liệu trong phạm vi được cấp", async () => { dbMocks.getInternalAccountByUserId.mockResolvedValue({ scopeUnits: JSON.stringify(["Đội 1"]), permissionProfile: JSON.stringify(["care:write"]) }); await expect(appRouter.createCaller(context("user")).operations.save(payload)).resolves.toEqual({ success: true }); await expect(appRouter.createCaller(context("user")).operations.save({ ...payload, unit: "Đội 2" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
});
